-- MySQL Script generated by MySQL Workbench
-- Tue May  3 22:15:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Cotejamiento: utf8_general_ci

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_cms_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_cms_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_cms_db` DEFAULT CHARACTER SET utf8 ;
USE `hospital_cms_db` ;

-- -----------------------------------------------------
-- Table `hospital_cms_db`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_cms_db`.`paciente` (
  `id_paciente` INT NOT NULL,
  `tipo_id` VARCHAR(45) NULL,
  `nombres_paciente` VARCHAR(45) NULL,
  `apellidos_paciente` VARCHAR(45) NULL,
  `fecha_nacimiente` DATE NULL,
  `direccion_residencia` VARCHAR(45) NULL,
  `num_celular` VARCHAR(45) NULL,
  `grupo_edad` VARCHAR(45) NULL,
  `genero_paciente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_cms_db`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_cms_db`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `tipo_id` VARCHAR(45) NULL,
  `numero_id_funcionario` VARCHAR(45) NULL,
  `nombres_funcionario` VARCHAR(45) NULL,
  `apellidos_funcionario` VARCHAR(45) NULL,
  `tipo_funcionario` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `profesion` VARCHAR(45) NULL,
  `num_celular` VARCHAR(11) NULL,
  `genero` CHAR NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_cms_db`.`vacuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_cms_db`.`vacuna` (
  `id_vacuna` INT NOT NULL,
  `nombre_vacuna` VARCHAR(55) NULL,
  `tipo_vacuna` VARCHAR(45) NULL,
  `lote` VARCHAR(45) NULL,
  `fecha_aplicada` DATE NULL,
  `fecha_vencimiento` DATE NULL,
  PRIMARY KEY (`id_vacuna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_cms_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_cms_db`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(55) NULL,
  `tipo_usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `funcionario_id_funcionario`),
  INDEX `fk_usuario_funcionario1_idx` (`funcionario_id_funcionario` ASC),
  CONSTRAINT `fk_usuario_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `hospital_cms_db`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_cms_db`.`dosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_cms_db`.`dosis` (
  `id_dosis` INT NOT NULL,
  `cantidad_dosis` VARCHAR(45) NULL,
  `fecha_dosis` DATE NULL,
  `fecha_segunda_dosis` DATE NULL,
  `paciente_id_paciente` INT NOT NULL,
  `vacuna_id_vacuna` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_dosis`),
  INDEX `fk_dosis_paciente1_idx` (`paciente_id_paciente` ASC),
  INDEX `fk_dosis_vacuna1_idx` (`vacuna_id_vacuna` ASC),
  INDEX `fk_dosis_funcionario1_idx` (`funcionario_id_funcionario` ASC),
  CONSTRAINT `fk_dosis_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital_cms_db`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dosis_vacuna1`
    FOREIGN KEY (`vacuna_id_vacuna`)
    REFERENCES `hospital_cms_db`.`vacuna` (`id_vacuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dosis_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `hospital_cms_db`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
